import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "The Blog - Este é um blog desenvolvido em Next.js",
    template: "%s | The Blog",
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-BR">
      <body>
        <Container>
          <Header />
          {children}
          <footer>
            <p className="py-8 text-center text-6xl font-bold">&copy; 2025</p>
          </footer>
        </Container>
      </body>
    </html>
  );
}
